### ISSUE TITLE
Enhance stats

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1393]
This issues serves the purpose to track all things that could be improved or implemented to make stats more accurate.

## This is an ever evolving list

- [ ] Pet perks that alter weapon, armor or stats directly
- [ ] Magic find from pet score
- [ ] Century cakes, see #1386
- [ ] Potion effects, see #1382 
- [ ] Dungeon shop upgrades, see #1385 
- [ ] Harp quest, see #1384 
- [ ] Accessory bag power and tuning, see #1381 
- [ ] Bestiary level (+2hp per level)
- [x] Reaper peppers (+1hp each)
- [ ] Harp intelligence bonus
- Reforges:
  - [ ] Renown
  - [ ] Loving, see #1419
- Armor set bonuses or abilities
  - [ ] Superior Dragon Armor
  - [ ] Young Dragon Armor
  - [ ] Cheap Tuxedo
  - [ ] Fancy Tuxedo
  - [ ] Elegant Tuxedo
  - [ ] Lapis Armor
  - [ ] Emerald Armor
  - [ ] Fairy Armor
  - [ ] Speedster Armor
  - [ ] Mastiff Armor
- Item abilities
  - [ ] Day Crystal
  - [ ] Night Crystal
  - [ ] Obsidian Chestplate
  - [ ] Speed Talisman
  - [ ] Speed Ring
  - [ ] Speed Artifact
  - [ ] Frozen Chicken
- Items giving personalized bonus based on kills or other things ("Kills: ", "Your Bonus: ", ...)

EHP?

---
**Also see `lib.js->getStats()`**

**Comment by DuckySoLucky** [comment]
~~Hey, letting u know that this stuff has been already done in~~ ~~[QwackAPI](https://github.com/DuckySoLucky/QwackAPI/blob/main/stats/stats.js).~~ ~~Accuracy isn't 100% there are some stuff which are not possible to make like Magic Find and Wisdom from Booster Cookie (Impossible to detect if player has an cookie or not, not in API I think, not 100% sure) and 1-10 Intelligence (Defuse Kit, not in API). Example of stats can be found~~ ~~[Here](https://github.com/DuckySoLucky/QwackAPI/blob/main/examples/v2/stats.json)~~.~~I have tested this on multiple profiles and accounts, accuracy is like 99% without taking in fact impossible stuff, mostly because Hypixel's WIKI's reforge information isn't 100% accurate.~~

~~I made this recently so code isn't really clean or fully optimized. I have to update some stuff like calculation so it uses names of items instead of IDs and stuff like that, but other than that it's pretty much complete~~

~~I'm planning to slowly integrate it into SkyCrypt, but recently I have been kind of busy so no ETA yet. Making this in case someone wants to work on this so he doesn't have to write everything again for no reason~~

**Comment by DuckySoLucky** [comment]
# Completion
- [x] Bestiary Level (Health)
- [x] Cake Bag (Health)
- [x] Catacombs Level (Health)
- [x] Reaper Peppers (Health)
- [x] Unique Pets (Magic Find)
- [x] Jacob's Farming Shop (Farming Fortune)
- [x] Permanent stats from Wither Essence Shop 
- [ ] ~~Fairy Souls~~ Replaced by levels, waiting for Hypixel
- [x] Slayer Level Up Bonus
- [x] Slayer Tier Completions (Combat Wisdom
- [x] Skill Level up (Carpentry is missing)
- [x] Equipment 
- [x] Active Accessories
- [x] Custom accessory abilities (Day/Night Crystal)
- [x] Current Reforge 
- [x] HOTM (Mining Fortune, Speed, Mining Wisdom)
- [x] Harp (Intelligence)
- [x] Armor 
- [x] Custom Armor Abilities (Superior, Young, Obsidian Chestplate etc..)
- [x] Active Pet
- [x] Custom Pet Abilities (Whale pet health multiplier, Ender Dragon stats Multiplier etc..)
- [x] Active Potion Effects

> Somehow find out if player has cookie or not. Otherwise 25 Wisdom on each stat and 15 Magic Find will be missing
